# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tllm/grpc/proto/schemas.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "tllm/grpc/proto/schemas.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dtllm/grpc/proto/schemas.proto\x12\x07schemas"-\n\x0e\x42\x46loat16Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05"\x1d\n\x08InputIds\x12\x11\n\tinput_ids\x18\x01 \x03(\x05"~\n\x0e\x46orwardRequest\x12\x11\n\tuuid_list\x18\x01 \x03(\t\x12)\n\x0einput_ids_list\x18\x02 \x03(\x0b\x32\x11.schemas.InputIds\x12.\n\rhidden_states\x18\x03 \x01(\x0b\x32\x17.schemas.BFloat16Tensor"@\n\rStatusRequest\x12\x0c\n\x04uuid\x18\x01 \x03(\t\x12\x0e\n\x06pp_idx\x18\x02 \x01(\x05\x12\x11\n\tcost_time\x18\x03 \x01(\x02"-\n\x0eStatusResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05".\n\x0f\x46orwardResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"-\n\x0eHealthResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"\x07\n\x05\x45mpty"L\n\x10SetConfigRequest\x12\x13\n\x0b\x66orward_url\x18\x01 \x01(\t\x12\x12\n\nmaster_url\x18\x02 \x01(\t\x12\x0f\n\x07pp_rank\x18\x03 \x01(\x05"0\n\x11SetConfigResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"\xed\x01\n\x13ImageForwardRequest\x12\x0c\n\x04uuid\x18\x01 \x03(\t\x12.\n\rhidden_states\x18\x02 \x01(\x0b\x32\x17.schemas.BFloat16Tensor\x12\x36\n\x15\x65ncoder_hidden_states\x18\x03 \x01(\x0b\x32\x17.schemas.BFloat16Tensor\x12\x30\n\x0ftext_embeddings\x18\x04 \x01(\x0b\x32\x17.schemas.BFloat16Tensor\x12\x0f\n\x07seq_len\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\r\n\x05width\x18\x07 \x01(\x05\x32\xc4\x02\n\nRPCService\x12\x39\n\x06Status\x12\x16.schemas.StatusRequest\x1a\x17.schemas.StatusResponse\x12<\n\x07\x46orward\x12\x17.schemas.ForwardRequest\x1a\x18.schemas.ForwardResponse\x12\x31\n\x06Health\x12\x0e.schemas.Empty\x1a\x17.schemas.HealthResponse\x12\x42\n\tSetConfig\x12\x19.schemas.SetConfigRequest\x1a\x1a.schemas.SetConfigResponse\x12\x46\n\x0cImageForward\x12\x1c.schemas.ImageForwardRequest\x1a\x18.schemas.ForwardResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tllm.grpc.proto.schemas_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BFLOAT16TENSOR"]._serialized_start = 42
    _globals["_BFLOAT16TENSOR"]._serialized_end = 87
    _globals["_INPUTIDS"]._serialized_start = 89
    _globals["_INPUTIDS"]._serialized_end = 118
    _globals["_FORWARDREQUEST"]._serialized_start = 120
    _globals["_FORWARDREQUEST"]._serialized_end = 246
    _globals["_STATUSREQUEST"]._serialized_start = 248
    _globals["_STATUSREQUEST"]._serialized_end = 312
    _globals["_STATUSRESPONSE"]._serialized_start = 314
    _globals["_STATUSRESPONSE"]._serialized_end = 359
    _globals["_FORWARDRESPONSE"]._serialized_start = 361
    _globals["_FORWARDRESPONSE"]._serialized_end = 407
    _globals["_HEALTHRESPONSE"]._serialized_start = 409
    _globals["_HEALTHRESPONSE"]._serialized_end = 454
    _globals["_EMPTY"]._serialized_start = 456
    _globals["_EMPTY"]._serialized_end = 463
    _globals["_SETCONFIGREQUEST"]._serialized_start = 465
    _globals["_SETCONFIGREQUEST"]._serialized_end = 541
    _globals["_SETCONFIGRESPONSE"]._serialized_start = 543
    _globals["_SETCONFIGRESPONSE"]._serialized_end = 591
    _globals["_IMAGEFORWARDREQUEST"]._serialized_start = 594
    _globals["_IMAGEFORWARDREQUEST"]._serialized_end = 831
    _globals["_RPCSERVICE"]._serialized_start = 834
    _globals["_RPCSERVICE"]._serialized_end = 1158
# @@protoc_insertion_point(module_scope)
