# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from tllm.grpc.proto import schemas_pb2 as tllm_dot_grpc_dot_proto_dot_schemas__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in tllm/grpc/proto/schemas_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
            "/schemas.RPCService/Status",
            request_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusRequest.SerializeToString,
            response_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusResponse.FromString,
            _registered_method=True,
        )
        self.Forward = channel.unary_unary(
            "/schemas.RPCService/Forward",
            request_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardRequest.SerializeToString,
            response_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/schemas.RPCService/Health",
            request_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.Empty.SerializeToString,
            response_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.SetConfig = channel.unary_unary(
            "/schemas.RPCService/SetConfig",
            request_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigRequest.SerializeToString,
            response_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigResponse.FromString,
            _registered_method=True,
        )
        self.ImageForward = channel.unary_unary(
            "/schemas.RPCService/ImageForward",
            request_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ImageForwardRequest.SerializeToString,
            response_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.FromString,
            _registered_method=True,
        )


class RPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImageForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Status": grpc.unary_unary_rpc_method_handler(
            servicer.Status,
            request_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusRequest.FromString,
            response_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusResponse.SerializeToString,
        ),
        "Forward": grpc.unary_unary_rpc_method_handler(
            servicer.Forward,
            request_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardRequest.FromString,
            response_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.Empty.FromString,
            response_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.HealthResponse.SerializeToString,
        ),
        "SetConfig": grpc.unary_unary_rpc_method_handler(
            servicer.SetConfig,
            request_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigRequest.FromString,
            response_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigResponse.SerializeToString,
        ),
        "ImageForward": grpc.unary_unary_rpc_method_handler(
            servicer.ImageForward,
            request_deserializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ImageForwardRequest.FromString,
            response_serializer=tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("schemas.RPCService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("schemas.RPCService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/schemas.RPCService/Status",
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusRequest.SerializeToString,
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Forward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/schemas.RPCService/Forward",
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardRequest.SerializeToString,
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/schemas.RPCService/Health",
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.Empty.SerializeToString,
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/schemas.RPCService/SetConfig",
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigRequest.SerializeToString,
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ImageForward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/schemas.RPCService/ImageForward",
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.ImageForwardRequest.SerializeToString,
            tllm_dot_grpc_dot_proto_dot_schemas__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
