# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tllm/rpc/schemas.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16tllm/rpc/schemas.proto\x12\x07schemas"-\n\x0e\x42\x46loat16Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05"_\n\x0e\x46orwardRequest\x12\x0c\n\x04uuid\x18\x01 \x03(\t\x12\x0f\n\x07seq_len\x18\x02 \x03(\x05\x12.\n\rhidden_states\x18\x03 \x01(\x0b\x32\x17.schemas.BFloat16Tensor"Q\n\rStatusRequest\x12\x0c\n\x04uuid\x18\x01 \x03(\t\x12\x0f\n\x07seq_len\x18\x02 \x03(\x05\x12\x0e\n\x06pp_idx\x18\x03 \x01(\x05\x12\x11\n\tcost_time\x18\x04 \x01(\x02"-\n\x0eStatusResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05".\n\x0f\x46orwardResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"-\n\x0eHealthResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"\x07\n\x05\x45mpty2\xb8\x01\n\nRPCService\x12\x39\n\x06Status\x12\x16.schemas.StatusRequest\x1a\x17.schemas.StatusResponse\x12<\n\x07\x46orward\x12\x17.schemas.ForwardRequest\x1a\x18.schemas.ForwardResponse\x12\x31\n\x06Health\x12\x0e.schemas.Empty\x1a\x17.schemas.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tllm.rpc.schemas_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BFLOAT16TENSOR"]._serialized_start = 35
    _globals["_BFLOAT16TENSOR"]._serialized_end = 80
    _globals["_FORWARDREQUEST"]._serialized_start = 82
    _globals["_FORWARDREQUEST"]._serialized_end = 177
    _globals["_STATUSREQUEST"]._serialized_start = 179
    _globals["_STATUSREQUEST"]._serialized_end = 260
    _globals["_STATUSRESPONSE"]._serialized_start = 262
    _globals["_STATUSRESPONSE"]._serialized_end = 307
    _globals["_FORWARDRESPONSE"]._serialized_start = 309
    _globals["_FORWARDRESPONSE"]._serialized_end = 355
    _globals["_HEALTHRESPONSE"]._serialized_start = 357
    _globals["_HEALTHRESPONSE"]._serialized_end = 402
    _globals["_EMPTY"]._serialized_start = 404
    _globals["_EMPTY"]._serialized_end = 411
    _globals["_RPCSERVICE"]._serialized_start = 414
    _globals["_RPCSERVICE"]._serialized_end = 598
# @@protoc_insertion_point(module_scope)
