# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src2/rpc_comm/schemas.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "src2/rpc_comm/schemas.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bsrc2/rpc_comm/schemas.proto\x12\x07schemas"\x19\n\x05\x41rray\x12\x10\n\x08\x65lements\x18\x01 \x03(\x02"&\n\x06Matrix\x12\x1c\n\x04rows\x18\x01 \x03(\x0b\x32\x0e.schemas.Array")\n\x06Tensor\x12\x1f\n\x06layers\x18\x01 \x03(\x0b\x32\x0f.schemas.Matrix".\n\x0b\x42lockTensor\x12\x1f\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x0f.schemas.Tensor"\xbb\x01\n\x15MultiDimensionalArray\x12\x1f\n\x05\x61rray\x18\x01 \x01(\x0b\x32\x0e.schemas.ArrayH\x00\x12!\n\x06matrix\x18\x02 \x01(\x0b\x32\x0f.schemas.MatrixH\x00\x12!\n\x06tensor\x18\x03 \x01(\x0b\x32\x0f.schemas.TensorH\x00\x12,\n\x0c\x62lock_tensor\x18\x04 \x01(\x0b\x32\x14.schemas.BlockTensorH\x00\x42\r\n\x0bmulti_array"\x8c\x01\n\x0bModelConfig\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0f\n\x07pp_rank\x18\x02 \x01(\x05\x12\x17\n\x0flayer_idx_start\x18\x03 \x01(\x05\x12\x15\n\rlayer_idx_end\x18\x04 \x01(\x05\x12\x12\n\nmaster_url\x18\x05 \x01(\t\x12\x14\n\x0cnext_pp_rank\x18\x06 \x01(\x05"U\n\x0e\x46orwardRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x35\n\rhidden_states\x18\x02 \x01(\x0b\x32\x1e.schemas.MultiDimensionalArray"-\n\x0eStatusResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"q\n\x0f\x46orwardResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12.\n\x06output\x18\x03 \x01(\x0b\x32\x1e.schemas.MultiDimensionalArray\x12\x11\n\tcost_time\x18\x04 \x01(\x02"-\n\x0eHealthResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05"4\n\x15InitModelFlagResponse\x12\x0b\n\x03msg\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\x05"\x07\n\x05\x45mpty2\xfa\x01\n\nRPCService\x12:\n\tInitModel\x12\x14.schemas.ModelConfig\x1a\x17.schemas.StatusResponse\x12<\n\x07\x46orward\x12\x17.schemas.ForwardRequest\x1a\x18.schemas.ForwardResponse\x12\x31\n\x06Health\x12\x0e.schemas.Empty\x1a\x17.schemas.HealthResponse\x12?\n\rInitModelFlag\x12\x0e.schemas.Empty\x1a\x1e.schemas.InitModelFlagResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "src2.rpc_comm.schemas_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ARRAY"]._serialized_start = 40
    _globals["_ARRAY"]._serialized_end = 65
    _globals["_MATRIX"]._serialized_start = 67
    _globals["_MATRIX"]._serialized_end = 105
    _globals["_TENSOR"]._serialized_start = 107
    _globals["_TENSOR"]._serialized_end = 148
    _globals["_BLOCKTENSOR"]._serialized_start = 150
    _globals["_BLOCKTENSOR"]._serialized_end = 196
    _globals["_MULTIDIMENSIONALARRAY"]._serialized_start = 199
    _globals["_MULTIDIMENSIONALARRAY"]._serialized_end = 386
    _globals["_MODELCONFIG"]._serialized_start = 389
    _globals["_MODELCONFIG"]._serialized_end = 529
    _globals["_FORWARDREQUEST"]._serialized_start = 531
    _globals["_FORWARDREQUEST"]._serialized_end = 616
    _globals["_STATUSRESPONSE"]._serialized_start = 618
    _globals["_STATUSRESPONSE"]._serialized_end = 663
    _globals["_FORWARDRESPONSE"]._serialized_start = 665
    _globals["_FORWARDRESPONSE"]._serialized_end = 778
    _globals["_HEALTHRESPONSE"]._serialized_start = 780
    _globals["_HEALTHRESPONSE"]._serialized_end = 825
    _globals["_INITMODELFLAGRESPONSE"]._serialized_start = 827
    _globals["_INITMODELFLAGRESPONSE"]._serialized_end = 879
    _globals["_EMPTY"]._serialized_start = 881
    _globals["_EMPTY"]._serialized_end = 888
    _globals["_RPCSERVICE"]._serialized_start = 891
    _globals["_RPCSERVICE"]._serialized_end = 1141
# @@protoc_insertion_point(module_scope)
